services:

  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hardware-acceleration.ms.yaml
      service: hardware-acceleration
    depends_on: [postgres, redis]
    env_file: environment.d/immich.env
    environment:
      DB_HOSTNAME: ${DATABASE_HOST:-postgres}
      DB_DATABASE_NAME: ${DATABASE_NAME:-immich}
      DB_USERNAME: ${DATABASE_USER:-immich}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: redis
      TZ: ${TZ:-UTC}
    ports:
      - ${IMMICH_SERVER_PORT:-2283}:2283
    volumes:
      - ${IMMICH_UPLOADS_PATH}:/usr/src/app/upload
      - ./volumes/config:/config:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends:
      file: hardware-acceleration.ml.yaml
      service: hardware-acceleration
    volumes:
      - ${MODEL_CACHE_VOLUME:-model-cache}:/cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: ${DATABASE_HOST:-postgres}
      DB_DATABASE_NAME: ${DATABASE_NAME:-immich}
      DB_USERNAME: ${DATABASE_USER:-immich}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: redis
      TZ: ${TZ:-UTC}
    restart: unless-stopped

  postgres:
    image: ghcr.io/immich-app/postgres:${POSTGRES_VERSION:-16-vectorchord0.4.2}
    env_file: environment.d/postgres.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-immich}
      POSTGRES_USER: ${DATABASE_USER:-immich}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DATABASE_VOLUME:-postgres-data}:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  redis:
    image: valkey/valkey:${VALKEY_VERSION:-8}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  postgres-data: {}
  model-cache: {}
