version: '3'

services:

  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    depends_on:
      - redis
      - postgres
      - typesense
    env_file: environment.d/immich.env
    environment:
      DB_HOSTNAME: ${DATABASE_HOST:-postgres}
      DB_DATABASE_NAME: ${DATABASE_NAME:-immich}
      DB_USERNAME: ${DATABASE_USER:-immich}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: redis
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TZ: ${TZ:-UTC}
    ports:
      - ${IMMICH_SERVER_PORT:-3001}:3001
    volumes:
      - ${IMMICH_UPLOADS_PATH}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: immich-compose
    restart: unless-stopped
  
  microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    extends:
      file: hardware-acceleration.yaml
      service: hardware-acceleration
    depends_on:
      - redis
      - postgres
      - typesense
    env_file: environment.d/immich.env
    environment:
      DB_HOSTNAME: ${DATABASE_HOST:-postgres}
      DB_DATABASE_NAME: ${DATABASE_NAME:-immich}
      DB_USERNAME: ${DATABASE_USER:-immich}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: redis
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TZ: ${TZ:-UTC}
    volumes:
      - ${IMMICH_UPLOADS_PATH}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    restart: always
  
  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${MODEL_CACHE_VOLUME:-model-cache}:/cache
    environment:
      DB_HOSTNAME: ${DATABASE_HOST:-postgres}
      DB_DATABASE_NAME: ${DATABASE_NAME:-immich}
      DB_USERNAME: ${DATABASE_USER:-immich}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOSTNAME: redis
      TZ: ${TZ:-UTC}
    restart: unless-stopped

  typesense:
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: /data
      GLOG_minloglevel: 1 # Remove to get debug messages
    volumes:
      - ${TYPESENSE_DATA_VOLUME:-typesense-data}:/data
    restart: unless-stopped

  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-immich}
      POSTGRES_USER: ${DATABASE_USER:-immich}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      TZ: ${TZ:-UTC}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      com.centurylinklabs.watchtower.scope: immich-compose
    restart: unless-stopped

  redis:
    image: redis:7.2
    labels:
      com.centurylinklabs.watchtower.scope: immich-compose
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: immich-compose
      TZ: ${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.scope: immich-compose
    restart: unless-stopped

volumes:
  postgres-data: {}
  model-cache: {}
  typesense-data: {}
